remote_theme: pages-themes/minimal@v0.2.0
plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
title: The HDF Group - ensuring long-term access and usability of HDF data and supporting users of HDF technologies
description: A new website using Pages!

logo: /assets/img/logo.png
show_downloads: false
site.github.is_user_page: false
google_analytics:
# theme: jekyll-theme-minimal
